// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/volumeplugin/v1/volumeplugin.proto

package volumepluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolumePluginService_Attach_FullMethodName = "/cubelet.services.volumeplugin.v1.VolumePluginService/Attach"
	VolumePluginService_Detach_FullMethodName = "/cubelet.services.volumeplugin.v1.VolumePluginService/Detach"
)

// VolumePluginServiceClient is the client API for VolumePluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VolumePluginService is the gRPC interface implemented by RPC-type plugins.
// The Cubelet VolumePlugin framework calls these RPCs instead of forking a
// subprocess.
type VolumePluginServiceClient interface {
	// Attach provisions the volume on the host and returns attach metadata.
	// Cubelet stores the returned metadata and passes it back unchanged on
	// Detach.
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error)
	// Detach tears down a previously attached volume.
	Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*DetachResponse, error)
}

type volumePluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumePluginServiceClient(cc grpc.ClientConnInterface) VolumePluginServiceClient {
	return &volumePluginServiceClient{cc}
}

func (c *volumePluginServiceClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachResponse)
	err := c.cc.Invoke(ctx, VolumePluginService_Attach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumePluginServiceClient) Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*DetachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachResponse)
	err := c.cc.Invoke(ctx, VolumePluginService_Detach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumePluginServiceServer is the server API for VolumePluginService service.
// All implementations must embed UnimplementedVolumePluginServiceServer
// for forward compatibility.
//
// VolumePluginService is the gRPC interface implemented by RPC-type plugins.
// The Cubelet VolumePlugin framework calls these RPCs instead of forking a
// subprocess.
type VolumePluginServiceServer interface {
	// Attach provisions the volume on the host and returns attach metadata.
	// Cubelet stores the returned metadata and passes it back unchanged on
	// Detach.
	Attach(context.Context, *AttachRequest) (*AttachResponse, error)
	// Detach tears down a previously attached volume.
	Detach(context.Context, *DetachRequest) (*DetachResponse, error)
	mustEmbedUnimplementedVolumePluginServiceServer()
}

// UnimplementedVolumePluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumePluginServiceServer struct{}

func (UnimplementedVolumePluginServiceServer) Attach(context.Context, *AttachRequest) (*AttachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedVolumePluginServiceServer) Detach(context.Context, *DetachRequest) (*DetachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detach not implemented")
}
func (UnimplementedVolumePluginServiceServer) mustEmbedUnimplementedVolumePluginServiceServer() {}
func (UnimplementedVolumePluginServiceServer) testEmbeddedByValue()                             {}

// UnsafeVolumePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumePluginServiceServer will
// result in compilation errors.
type UnsafeVolumePluginServiceServer interface {
	mustEmbedUnimplementedVolumePluginServiceServer()
}

func RegisterVolumePluginServiceServer(s grpc.ServiceRegistrar, srv VolumePluginServiceServer) {
	// If the following call panics, it indicates UnimplementedVolumePluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumePluginService_ServiceDesc, srv)
}

func _VolumePluginService_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumePluginServiceServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumePluginService_Attach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumePluginServiceServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumePluginService_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumePluginServiceServer).Detach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumePluginService_Detach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumePluginServiceServer).Detach(ctx, req.(*DetachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumePluginService_ServiceDesc is the grpc.ServiceDesc for VolumePluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumePluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.volumeplugin.v1.VolumePluginService",
	HandlerType: (*VolumePluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attach",
			Handler:    _VolumePluginService_Attach_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _VolumePluginService_Detach_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/volumeplugin/v1/volumeplugin.proto",
}

const (
	VolumeControllerService_Create_FullMethodName  = "/cubelet.services.volumeplugin.v1.VolumeControllerService/Create"
	VolumeControllerService_Destroy_FullMethodName = "/cubelet.services.volumeplugin.v1.VolumeControllerService/Destroy"
)

// VolumeControllerServiceClient is the client API for VolumeControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VolumeControllerService is the gRPC interface for CubeMaster Controller hooks.
// RPC-type plugins implement this service alongside VolumePluginService (Node).
type VolumeControllerServiceClient interface {
	// Create provisions a new volume in the backend storage.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Destroy permanently deletes a volume and its backend data.
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
}

type volumeControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeControllerServiceClient(cc grpc.ClientConnInterface) VolumeControllerServiceClient {
	return &volumeControllerServiceClient{cc}
}

func (c *volumeControllerServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, VolumeControllerService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeControllerServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, VolumeControllerService_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeControllerServiceServer is the server API for VolumeControllerService service.
// All implementations must embed UnimplementedVolumeControllerServiceServer
// for forward compatibility.
//
// VolumeControllerService is the gRPC interface for CubeMaster Controller hooks.
// RPC-type plugins implement this service alongside VolumePluginService (Node).
type VolumeControllerServiceServer interface {
	// Create provisions a new volume in the backend storage.
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Destroy permanently deletes a volume and its backend data.
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	mustEmbedUnimplementedVolumeControllerServiceServer()
}

// UnimplementedVolumeControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeControllerServiceServer struct{}

func (UnimplementedVolumeControllerServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVolumeControllerServiceServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedVolumeControllerServiceServer) mustEmbedUnimplementedVolumeControllerServiceServer() {
}
func (UnimplementedVolumeControllerServiceServer) testEmbeddedByValue() {}

// UnsafeVolumeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeControllerServiceServer will
// result in compilation errors.
type UnsafeVolumeControllerServiceServer interface {
	mustEmbedUnimplementedVolumeControllerServiceServer()
}

func RegisterVolumeControllerServiceServer(s grpc.ServiceRegistrar, srv VolumeControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedVolumeControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeControllerService_ServiceDesc, srv)
}

func _VolumeControllerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeControllerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeControllerService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeControllerServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeControllerService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeControllerServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeControllerService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeControllerServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeControllerService_ServiceDesc is the grpc.ServiceDesc for VolumeControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.volumeplugin.v1.VolumeControllerService",
	HandlerType: (*VolumeControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VolumeControllerService_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _VolumeControllerService_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/volumeplugin/v1/volumeplugin.proto",
}
