// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/volumeplugin/v1/volumeplugin.proto

package volumepluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginVolumeSource selects an external volume plugin by driver name.
// Embedded in cubebox.VolumeSource.
type PluginVolumeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// driver is the registered plugin name (e.g. "nfs", "s3fuse", "cfs").
	// Must match VolumePlugin.Name() on the Cubelet node.
	Driver        string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginVolumeSource) Reset() {
	*x = PluginVolumeSource{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginVolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginVolumeSource) ProtoMessage() {}

func (x *PluginVolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginVolumeSource.ProtoReflect.Descriptor instead.
func (*PluginVolumeSource) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginVolumeSource) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type AttachRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sandbox_id is the sandbox being created.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// namespace is the containerd namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// volume_id is the CubeMaster VolumeRecord identifier.
	// Used as the ref-count DB key for cross-sandbox deduplication.
	VolumeId string `protobuf:"bytes,3,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// volume_base_dir is the parent directory that Cubelet requires the plugin
	// to mount this volume under. The plugin MUST return a host_path located
	// inside this directory (typically "<volume_base_dir>/<plugin>-<volume_id>").
	// Cubelet rejects the attach if host_path is not within volume_base_dir.
	VolumeBaseDir string `protobuf:"bytes,5,opt,name=volume_base_dir,json=volumeBaseDir,proto3" json:"volume_base_dir,omitempty"`
	// ref_count is the number of sandboxes already attached to this volume
	// BEFORE this call (i.e. the pre-attach count).
	// 0 → first attach; plugin should perform host-level setup.
	RefCount int64 `protobuf:"varint,6,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	// private_data is opaque plugin state returned by Create and persisted in
	// t_cube_volume. CubeMaster forwards it on sandbox create so Attach can
	// reuse Create-time context without a second control-plane round-trip.
	// Max length: 1024 bytes. May be empty.
	PrivateData   string `protobuf:"bytes,7,opt,name=private_data,json=privateData,proto3" json:"private_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{1}
}

func (x *AttachRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *AttachRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AttachRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *AttachRequest) GetVolumeBaseDir() string {
	if x != nil {
		return x.VolumeBaseDir
	}
	return ""
}

func (x *AttachRequest) GetRefCount() int64 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *AttachRequest) GetPrivateData() string {
	if x != nil {
		return x.PrivateData
	}
	return ""
}

type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_path is the host-side path cubelet exposes into the VM.
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// metadata is opaque key-value data cubelet persists and passes back
	// unchanged to Detach.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{2}
}

func (x *AttachResponse) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *AttachResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DetachRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	VolumeId  string                 `protobuf:"bytes,3,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// metadata is the exact map returned by the corresponding Attach call.
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ref_count is the number of sandboxes still attached AFTER this call
	// (i.e. the post-detach count).
	// 0 → last detach; plugin should tear down host-level resources.
	RefCount      int64 `protobuf:"varint,8,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachRequest) Reset() {
	*x = DetachRequest{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachRequest) ProtoMessage() {}

func (x *DetachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachRequest.ProtoReflect.Descriptor instead.
func (*DetachRequest) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{3}
}

func (x *DetachRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *DetachRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DetachRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *DetachRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DetachRequest) GetRefCount() int64 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

type DetachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachResponse) Reset() {
	*x = DetachResponse{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachResponse) ProtoMessage() {}

func (x *DetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachResponse.ProtoReflect.Descriptor instead.
func (*DetachResponse) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{4}
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the stable identifier assigned by CubeMaster.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// name is the human-readable label.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is an optional credential for volume-content access.
	// volume_id and name come from the CreateRequest; plugins must not echo them.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// private_data is opaque plugin state persisted in t_cube_volume and
	// forwarded to Attach on sandbox create. Not returned to API/SDK clients.
	// Max length: 1024 bytes. May be empty.
	PrivateData   string `protobuf:"bytes,2,opt,name=private_data,json=privateData,proto3" json:"private_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateResponse) GetPrivateData() string {
	if x != nil {
		return x.PrivateData
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP(), []int{8}
}

var File_api_services_volumeplugin_v1_volumeplugin_proto protoreflect.FileDescriptor

const file_api_services_volumeplugin_v1_volumeplugin_proto_rawDesc = "" +
	"\n" +
	"/api/services/volumeplugin/v1/volumeplugin.proto\x12 cubelet.services.volumeplugin.v1\",\n" +
	"\x12PluginVolumeSource\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\"\xd7\x01\n" +
	"\rAttachRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tvolume_id\x18\x03 \x01(\tR\bvolumeId\x12&\n" +
	"\x0fvolume_base_dir\x18\x05 \x01(\tR\rvolumeBaseDir\x12\x1b\n" +
	"\tref_count\x18\x06 \x01(\x03R\brefCount\x12!\n" +
	"\fprivate_data\x18\a \x01(\tR\vprivateDataJ\x04\b\x04\x10\x05\"\xd2\x01\n" +
	"\x0eAttachResponse\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12Z\n" +
	"\bmetadata\x18\x04 \x03(\v2>.cubelet.services.volumeplugin.v1.AttachResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02J\x04\b\x03\x10\x04\"\xaa\x02\n" +
	"\rDetachRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tvolume_id\x18\x03 \x01(\tR\bvolumeId\x12Y\n" +
	"\bmetadata\x18\x06 \x03(\v2=.cubelet.services.volumeplugin.v1.DetachRequest.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tref_count\x18\b \x01(\x03R\brefCount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x04\x10\x05J\x04\b\a\x10\b\"\x10\n" +
	"\x0eDetachResponse\"F\n" +
	"\rCreateRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameJ\x04\b\x03\x10\x04\"I\n" +
	"\x0eCreateResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fprivate_data\x18\x02 \x01(\tR\vprivateData\"3\n" +
	"\x0eDestroyRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeIdJ\x04\b\x02\x10\x03\"\x11\n" +
	"\x0fDestroyResponse2\xef\x01\n" +
	"\x13VolumePluginService\x12k\n" +
	"\x06Attach\x12/.cubelet.services.volumeplugin.v1.AttachRequest\x1a0.cubelet.services.volumeplugin.v1.AttachResponse\x12k\n" +
	"\x06Detach\x12/.cubelet.services.volumeplugin.v1.DetachRequest\x1a0.cubelet.services.volumeplugin.v1.DetachResponse2\xf6\x01\n" +
	"\x17VolumeControllerService\x12k\n" +
	"\x06Create\x12/.cubelet.services.volumeplugin.v1.CreateRequest\x1a0.cubelet.services.volumeplugin.v1.CreateResponse\x12n\n" +
	"\aDestroy\x120.cubelet.services.volumeplugin.v1.DestroyRequest\x1a1.cubelet.services.volumeplugin.v1.DestroyResponseBYZWgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/volumeplugin/v1;volumepluginv1b\x06proto3"

var (
	file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescOnce sync.Once
	file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescData []byte
)

func file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescGZIP() []byte {
	file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescOnce.Do(func() {
		file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_volumeplugin_v1_volumeplugin_proto_rawDesc), len(file_api_services_volumeplugin_v1_volumeplugin_proto_rawDesc)))
	})
	return file_api_services_volumeplugin_v1_volumeplugin_proto_rawDescData
}

var file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_services_volumeplugin_v1_volumeplugin_proto_goTypes = []any{
	(*PluginVolumeSource)(nil), // 0: cubelet.services.volumeplugin.v1.PluginVolumeSource
	(*AttachRequest)(nil),      // 1: cubelet.services.volumeplugin.v1.AttachRequest
	(*AttachResponse)(nil),     // 2: cubelet.services.volumeplugin.v1.AttachResponse
	(*DetachRequest)(nil),      // 3: cubelet.services.volumeplugin.v1.DetachRequest
	(*DetachResponse)(nil),     // 4: cubelet.services.volumeplugin.v1.DetachResponse
	(*CreateRequest)(nil),      // 5: cubelet.services.volumeplugin.v1.CreateRequest
	(*CreateResponse)(nil),     // 6: cubelet.services.volumeplugin.v1.CreateResponse
	(*DestroyRequest)(nil),     // 7: cubelet.services.volumeplugin.v1.DestroyRequest
	(*DestroyResponse)(nil),    // 8: cubelet.services.volumeplugin.v1.DestroyResponse
	nil,                        // 9: cubelet.services.volumeplugin.v1.AttachResponse.MetadataEntry
	nil,                        // 10: cubelet.services.volumeplugin.v1.DetachRequest.MetadataEntry
}
var file_api_services_volumeplugin_v1_volumeplugin_proto_depIdxs = []int32{
	9,  // 0: cubelet.services.volumeplugin.v1.AttachResponse.metadata:type_name -> cubelet.services.volumeplugin.v1.AttachResponse.MetadataEntry
	10, // 1: cubelet.services.volumeplugin.v1.DetachRequest.metadata:type_name -> cubelet.services.volumeplugin.v1.DetachRequest.MetadataEntry
	1,  // 2: cubelet.services.volumeplugin.v1.VolumePluginService.Attach:input_type -> cubelet.services.volumeplugin.v1.AttachRequest
	3,  // 3: cubelet.services.volumeplugin.v1.VolumePluginService.Detach:input_type -> cubelet.services.volumeplugin.v1.DetachRequest
	5,  // 4: cubelet.services.volumeplugin.v1.VolumeControllerService.Create:input_type -> cubelet.services.volumeplugin.v1.CreateRequest
	7,  // 5: cubelet.services.volumeplugin.v1.VolumeControllerService.Destroy:input_type -> cubelet.services.volumeplugin.v1.DestroyRequest
	2,  // 6: cubelet.services.volumeplugin.v1.VolumePluginService.Attach:output_type -> cubelet.services.volumeplugin.v1.AttachResponse
	4,  // 7: cubelet.services.volumeplugin.v1.VolumePluginService.Detach:output_type -> cubelet.services.volumeplugin.v1.DetachResponse
	6,  // 8: cubelet.services.volumeplugin.v1.VolumeControllerService.Create:output_type -> cubelet.services.volumeplugin.v1.CreateResponse
	8,  // 9: cubelet.services.volumeplugin.v1.VolumeControllerService.Destroy:output_type -> cubelet.services.volumeplugin.v1.DestroyResponse
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_services_volumeplugin_v1_volumeplugin_proto_init() }
func file_api_services_volumeplugin_v1_volumeplugin_proto_init() {
	if File_api_services_volumeplugin_v1_volumeplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_volumeplugin_v1_volumeplugin_proto_rawDesc), len(file_api_services_volumeplugin_v1_volumeplugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_services_volumeplugin_v1_volumeplugin_proto_goTypes,
		DependencyIndexes: file_api_services_volumeplugin_v1_volumeplugin_proto_depIdxs,
		MessageInfos:      file_api_services_volumeplugin_v1_volumeplugin_proto_msgTypes,
	}.Build()
	File_api_services_volumeplugin_v1_volumeplugin_proto = out.File
	file_api_services_volumeplugin_v1_volumeplugin_proto_goTypes = nil
	file_api_services_volumeplugin_v1_volumeplugin_proto_depIdxs = nil
}
