{{- if and .Values.volumeCos.enabled (not .Values.volumeCos.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cube.volumeCosSecretName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: volume-cos
type: Opaque
stringData:
  volume-cos.conf: |
    SECRET_ID={{ .Values.volumeCos.secretId }}
    SECRET_KEY={{ .Values.volumeCos.secretKey }}
    BUCKET={{ .Values.volumeCos.bucket }}
    REGION={{ .Values.volumeCos.region }}
{{- end }}
