// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: api/services/cubebox/v1/cubebox.proto

package cubebox

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CubeboxMgr_Create_FullMethodName                       = "/cubelet.services.cubebox.v1.CubeboxMgr/Create"
	CubeboxMgr_Destroy_FullMethodName                      = "/cubelet.services.cubebox.v1.CubeboxMgr/Destroy"
	CubeboxMgr_List_FullMethodName                         = "/cubelet.services.cubebox.v1.CubeboxMgr/List"
	CubeboxMgr_Update_FullMethodName                       = "/cubelet.services.cubebox.v1.CubeboxMgr/Update"
	CubeboxMgr_Exec_FullMethodName                         = "/cubelet.services.cubebox.v1.CubeboxMgr/Exec"
	CubeboxMgr_AppSnapshot_FullMethodName                  = "/cubelet.services.cubebox.v1.CubeboxMgr/AppSnapshot"
	CubeboxMgr_CommitSandbox_FullMethodName                = "/cubelet.services.cubebox.v1.CubeboxMgr/CommitSandbox"
	CubeboxMgr_RollbackSandbox_FullMethodName              = "/cubelet.services.cubebox.v1.CubeboxMgr/RollbackSandbox"
	CubeboxMgr_CleanupTemplate_FullMethodName              = "/cubelet.services.cubebox.v1.CubeboxMgr/CleanupTemplate"
	CubeboxMgr_ListSandboxSnapshots_FullMethodName         = "/cubelet.services.cubebox.v1.CubeboxMgr/ListSandboxSnapshots"
	CubeboxMgr_ListLocalSnapshots_FullMethodName           = "/cubelet.services.cubebox.v1.CubeboxMgr/ListLocalSnapshots"
	CubeboxMgr_GetLocalSnapshot_FullMethodName             = "/cubelet.services.cubebox.v1.CubeboxMgr/GetLocalSnapshot"
	CubeboxMgr_ExportTemplateRootfsArtifact_FullMethodName = "/cubelet.services.cubebox.v1.CubeboxMgr/ExportTemplateRootfsArtifact"
	CubeboxMgr_GetStorageMetrics_FullMethodName            = "/cubelet.services.cubebox.v1.CubeboxMgr/GetStorageMetrics"
	CubeboxMgr_InspectStorageVolumes_FullMethodName        = "/cubelet.services.cubebox.v1.CubeboxMgr/InspectStorageVolumes"
	CubeboxMgr_CleanupOrphanStorageFiles_FullMethodName    = "/cubelet.services.cubebox.v1.CubeboxMgr/CleanupOrphanStorageFiles"
)

// CubeboxMgrClient is the client API for CubeboxMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for handling cubesandbox
type CubeboxMgrClient interface {
	Create(ctx context.Context, in *RunCubeSandboxRequest, opts ...grpc.CallOption) (*RunCubeSandboxResponse, error)
	Destroy(ctx context.Context, in *DestroyCubeSandboxRequest, opts ...grpc.CallOption) (*DestroyCubeSandboxResponse, error)
	List(ctx context.Context, in *ListCubeSandboxRequest, opts ...grpc.CallOption) (*ListCubeSandboxResponse, error)
	Update(ctx context.Context, in *UpdateCubeSandboxRequest, opts ...grpc.CallOption) (*UpdateCubeSandboxResponse, error)
	Exec(ctx context.Context, in *ExecCubeSandboxRequest, opts ...grpc.CallOption) (*ExecCubeSandboxResponse, error)
	// AppSnapshot creates a cubebox, makes an app snapshot, and destroys the cubebox.
	// Required annotations:
	//   - cube.master.appsnapshot.create: "true"
	//   - cube.master.appsnapshot.template.id: "<template_id>"
	AppSnapshot(ctx context.Context, in *AppSnapshotRequest, opts ...grpc.CallOption) (*AppSnapshotResponse, error)
	// CommitSandbox snapshots an existing running sandbox into a template snapshot.
	CommitSandbox(ctx context.Context, in *CommitSandboxRequest, opts ...grpc.CallOption) (*CommitSandboxResponse, error)
	// RollbackSandbox restores a running sandbox to a committed snapshot.
	RollbackSandbox(ctx context.Context, in *RollbackSandboxRequest, opts ...grpc.CallOption) (*RollbackSandboxResponse, error)
	// CleanupTemplate removes local template snapshot/base data from this node.
	CleanupTemplate(ctx context.Context, in *CleanupTemplateRequest, opts ...grpc.CallOption) (*CleanupTemplateResponse, error)
	// ListSandboxSnapshots inspects the requested snapshot objects on this node.
	ListSandboxSnapshots(ctx context.Context, in *ListSandboxSnapshotsRequest, opts ...grpc.CallOption) (*ListSandboxSnapshotsResponse, error)
	// ListLocalSnapshots returns the full catalog of snapshots known to this node.
	// It is intended for master discovery / inspection so master does not need to
	// persist physical references (vol/dev/path/meta_dir) in its tables.
	ListLocalSnapshots(ctx context.Context, in *ListLocalSnapshotsRequest, opts ...grpc.CallOption) (*ListLocalSnapshotsResponse, error)
	// GetLocalSnapshot returns the physical catalog entry for a single snapshot
	// by snapshot id. Returns PreConditionFailed when no local record exists.
	GetLocalSnapshot(ctx context.Context, in *GetLocalSnapshotRequest, opts ...grpc.CallOption) (*GetLocalSnapshotResponse, error)
	// ExportTemplateRootfsArtifact streams the committed rootfs ext4 bytes for a
	// locally committed template so master can register and distribute it as a
	// normal RootfsArtifact.
	ExportTemplateRootfsArtifact(ctx context.Context, in *ExportTemplateRootfsArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportTemplateRootfsArtifactChunk], error)
	// GetStorageMetrics returns node-local cubecow storage metrics.
	GetStorageMetrics(ctx context.Context, in *GetStorageMetricsRequest, opts ...grpc.CallOption) (*GetStorageMetricsResponse, error)
	// InspectStorageVolumes lists every sandbox storage record cubelet owns and
	// re-resolves cubecow device paths so cubecli can render an authoritative
	// view without touching boltdb or the cubecow SDK directly.
	InspectStorageVolumes(ctx context.Context, in *InspectStorageVolumesRequest, opts ...grpc.CallOption) (*InspectStorageVolumesResponse, error)
	// CleanupOrphanStorageFiles scans configured emptydir format roots, drops
	// files that have no live sandbox owner, and reports the action taken.
	CleanupOrphanStorageFiles(ctx context.Context, in *CleanupOrphanStorageFilesRequest, opts ...grpc.CallOption) (*CleanupOrphanStorageFilesResponse, error)
}

type cubeboxMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeboxMgrClient(cc grpc.ClientConnInterface) CubeboxMgrClient {
	return &cubeboxMgrClient{cc}
}

func (c *cubeboxMgrClient) Create(ctx context.Context, in *RunCubeSandboxRequest, opts ...grpc.CallOption) (*RunCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Destroy(ctx context.Context, in *DestroyCubeSandboxRequest, opts ...grpc.CallOption) (*DestroyCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) List(ctx context.Context, in *ListCubeSandboxRequest, opts ...grpc.CallOption) (*ListCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Update(ctx context.Context, in *UpdateCubeSandboxRequest, opts ...grpc.CallOption) (*UpdateCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Exec(ctx context.Context, in *ExecCubeSandboxRequest, opts ...grpc.CallOption) (*ExecCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) AppSnapshot(ctx context.Context, in *AppSnapshotRequest, opts ...grpc.CallOption) (*AppSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSnapshotResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_AppSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) CommitSandbox(ctx context.Context, in *CommitSandboxRequest, opts ...grpc.CallOption) (*CommitSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_CommitSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) RollbackSandbox(ctx context.Context, in *RollbackSandboxRequest, opts ...grpc.CallOption) (*RollbackSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_RollbackSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) CleanupTemplate(ctx context.Context, in *CleanupTemplateRequest, opts ...grpc.CallOption) (*CleanupTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupTemplateResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_CleanupTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) ListSandboxSnapshots(ctx context.Context, in *ListSandboxSnapshotsRequest, opts ...grpc.CallOption) (*ListSandboxSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxSnapshotsResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_ListSandboxSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) ListLocalSnapshots(ctx context.Context, in *ListLocalSnapshotsRequest, opts ...grpc.CallOption) (*ListLocalSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocalSnapshotsResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_ListLocalSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) GetLocalSnapshot(ctx context.Context, in *GetLocalSnapshotRequest, opts ...grpc.CallOption) (*GetLocalSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalSnapshotResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_GetLocalSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) ExportTemplateRootfsArtifact(ctx context.Context, in *ExportTemplateRootfsArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportTemplateRootfsArtifactChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CubeboxMgr_ServiceDesc.Streams[0], CubeboxMgr_ExportTemplateRootfsArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportTemplateRootfsArtifactRequest, ExportTemplateRootfsArtifactChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CubeboxMgr_ExportTemplateRootfsArtifactClient = grpc.ServerStreamingClient[ExportTemplateRootfsArtifactChunk]

func (c *cubeboxMgrClient) GetStorageMetrics(ctx context.Context, in *GetStorageMetricsRequest, opts ...grpc.CallOption) (*GetStorageMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageMetricsResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_GetStorageMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) InspectStorageVolumes(ctx context.Context, in *InspectStorageVolumesRequest, opts ...grpc.CallOption) (*InspectStorageVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectStorageVolumesResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_InspectStorageVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) CleanupOrphanStorageFiles(ctx context.Context, in *CleanupOrphanStorageFilesRequest, opts ...grpc.CallOption) (*CleanupOrphanStorageFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupOrphanStorageFilesResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_CleanupOrphanStorageFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeboxMgrServer is the server API for CubeboxMgr service.
// All implementations must embed UnimplementedCubeboxMgrServer
// for forward compatibility.
//
// Service for handling cubesandbox
type CubeboxMgrServer interface {
	Create(context.Context, *RunCubeSandboxRequest) (*RunCubeSandboxResponse, error)
	Destroy(context.Context, *DestroyCubeSandboxRequest) (*DestroyCubeSandboxResponse, error)
	List(context.Context, *ListCubeSandboxRequest) (*ListCubeSandboxResponse, error)
	Update(context.Context, *UpdateCubeSandboxRequest) (*UpdateCubeSandboxResponse, error)
	Exec(context.Context, *ExecCubeSandboxRequest) (*ExecCubeSandboxResponse, error)
	// AppSnapshot creates a cubebox, makes an app snapshot, and destroys the cubebox.
	// Required annotations:
	//   - cube.master.appsnapshot.create: "true"
	//   - cube.master.appsnapshot.template.id: "<template_id>"
	AppSnapshot(context.Context, *AppSnapshotRequest) (*AppSnapshotResponse, error)
	// CommitSandbox snapshots an existing running sandbox into a template snapshot.
	CommitSandbox(context.Context, *CommitSandboxRequest) (*CommitSandboxResponse, error)
	// RollbackSandbox restores a running sandbox to a committed snapshot.
	RollbackSandbox(context.Context, *RollbackSandboxRequest) (*RollbackSandboxResponse, error)
	// CleanupTemplate removes local template snapshot/base data from this node.
	CleanupTemplate(context.Context, *CleanupTemplateRequest) (*CleanupTemplateResponse, error)
	// ListSandboxSnapshots inspects the requested snapshot objects on this node.
	ListSandboxSnapshots(context.Context, *ListSandboxSnapshotsRequest) (*ListSandboxSnapshotsResponse, error)
	// ListLocalSnapshots returns the full catalog of snapshots known to this node.
	// It is intended for master discovery / inspection so master does not need to
	// persist physical references (vol/dev/path/meta_dir) in its tables.
	ListLocalSnapshots(context.Context, *ListLocalSnapshotsRequest) (*ListLocalSnapshotsResponse, error)
	// GetLocalSnapshot returns the physical catalog entry for a single snapshot
	// by snapshot id. Returns PreConditionFailed when no local record exists.
	GetLocalSnapshot(context.Context, *GetLocalSnapshotRequest) (*GetLocalSnapshotResponse, error)
	// ExportTemplateRootfsArtifact streams the committed rootfs ext4 bytes for a
	// locally committed template so master can register and distribute it as a
	// normal RootfsArtifact.
	ExportTemplateRootfsArtifact(*ExportTemplateRootfsArtifactRequest, grpc.ServerStreamingServer[ExportTemplateRootfsArtifactChunk]) error
	// GetStorageMetrics returns node-local cubecow storage metrics.
	GetStorageMetrics(context.Context, *GetStorageMetricsRequest) (*GetStorageMetricsResponse, error)
	// InspectStorageVolumes lists every sandbox storage record cubelet owns and
	// re-resolves cubecow device paths so cubecli can render an authoritative
	// view without touching boltdb or the cubecow SDK directly.
	InspectStorageVolumes(context.Context, *InspectStorageVolumesRequest) (*InspectStorageVolumesResponse, error)
	// CleanupOrphanStorageFiles scans configured emptydir format roots, drops
	// files that have no live sandbox owner, and reports the action taken.
	CleanupOrphanStorageFiles(context.Context, *CleanupOrphanStorageFilesRequest) (*CleanupOrphanStorageFilesResponse, error)
	mustEmbedUnimplementedCubeboxMgrServer()
}

// UnimplementedCubeboxMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeboxMgrServer struct{}

func (UnimplementedCubeboxMgrServer) Create(context.Context, *RunCubeSandboxRequest) (*RunCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCubeboxMgrServer) Destroy(context.Context, *DestroyCubeSandboxRequest) (*DestroyCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedCubeboxMgrServer) List(context.Context, *ListCubeSandboxRequest) (*ListCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCubeboxMgrServer) Update(context.Context, *UpdateCubeSandboxRequest) (*UpdateCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCubeboxMgrServer) Exec(context.Context, *ExecCubeSandboxRequest) (*ExecCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedCubeboxMgrServer) AppSnapshot(context.Context, *AppSnapshotRequest) (*AppSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppSnapshot not implemented")
}
func (UnimplementedCubeboxMgrServer) CommitSandbox(context.Context, *CommitSandboxRequest) (*CommitSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitSandbox not implemented")
}
func (UnimplementedCubeboxMgrServer) RollbackSandbox(context.Context, *RollbackSandboxRequest) (*RollbackSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackSandbox not implemented")
}
func (UnimplementedCubeboxMgrServer) CleanupTemplate(context.Context, *CleanupTemplateRequest) (*CleanupTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupTemplate not implemented")
}
func (UnimplementedCubeboxMgrServer) ListSandboxSnapshots(context.Context, *ListSandboxSnapshotsRequest) (*ListSandboxSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxSnapshots not implemented")
}
func (UnimplementedCubeboxMgrServer) ListLocalSnapshots(context.Context, *ListLocalSnapshotsRequest) (*ListLocalSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLocalSnapshots not implemented")
}
func (UnimplementedCubeboxMgrServer) GetLocalSnapshot(context.Context, *GetLocalSnapshotRequest) (*GetLocalSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocalSnapshot not implemented")
}
func (UnimplementedCubeboxMgrServer) ExportTemplateRootfsArtifact(*ExportTemplateRootfsArtifactRequest, grpc.ServerStreamingServer[ExportTemplateRootfsArtifactChunk]) error {
	return status.Error(codes.Unimplemented, "method ExportTemplateRootfsArtifact not implemented")
}
func (UnimplementedCubeboxMgrServer) GetStorageMetrics(context.Context, *GetStorageMetricsRequest) (*GetStorageMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageMetrics not implemented")
}
func (UnimplementedCubeboxMgrServer) InspectStorageVolumes(context.Context, *InspectStorageVolumesRequest) (*InspectStorageVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectStorageVolumes not implemented")
}
func (UnimplementedCubeboxMgrServer) CleanupOrphanStorageFiles(context.Context, *CleanupOrphanStorageFilesRequest) (*CleanupOrphanStorageFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupOrphanStorageFiles not implemented")
}
func (UnimplementedCubeboxMgrServer) mustEmbedUnimplementedCubeboxMgrServer() {}
func (UnimplementedCubeboxMgrServer) testEmbeddedByValue()                    {}

// UnsafeCubeboxMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeboxMgrServer will
// result in compilation errors.
type UnsafeCubeboxMgrServer interface {
	mustEmbedUnimplementedCubeboxMgrServer()
}

func RegisterCubeboxMgrServer(s grpc.ServiceRegistrar, srv CubeboxMgrServer) {
	// If the following call panics, it indicates UnimplementedCubeboxMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeboxMgr_ServiceDesc, srv)
}

func _CubeboxMgr_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Create(ctx, req.(*RunCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Destroy(ctx, req.(*DestroyCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).List(ctx, req.(*ListCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Update(ctx, req.(*UpdateCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Exec(ctx, req.(*ExecCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_AppSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).AppSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_AppSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).AppSnapshot(ctx, req.(*AppSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_CommitSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).CommitSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_CommitSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).CommitSandbox(ctx, req.(*CommitSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_RollbackSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).RollbackSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_RollbackSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).RollbackSandbox(ctx, req.(*RollbackSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_CleanupTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).CleanupTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_CleanupTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).CleanupTemplate(ctx, req.(*CleanupTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_ListSandboxSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).ListSandboxSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_ListSandboxSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).ListSandboxSnapshots(ctx, req.(*ListSandboxSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_ListLocalSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocalSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).ListLocalSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_ListLocalSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).ListLocalSnapshots(ctx, req.(*ListLocalSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_GetLocalSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).GetLocalSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_GetLocalSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).GetLocalSnapshot(ctx, req.(*GetLocalSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_ExportTemplateRootfsArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportTemplateRootfsArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CubeboxMgrServer).ExportTemplateRootfsArtifact(m, &grpc.GenericServerStream[ExportTemplateRootfsArtifactRequest, ExportTemplateRootfsArtifactChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CubeboxMgr_ExportTemplateRootfsArtifactServer = grpc.ServerStreamingServer[ExportTemplateRootfsArtifactChunk]

func _CubeboxMgr_GetStorageMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).GetStorageMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_GetStorageMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).GetStorageMetrics(ctx, req.(*GetStorageMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_InspectStorageVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectStorageVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).InspectStorageVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_InspectStorageVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).InspectStorageVolumes(ctx, req.(*InspectStorageVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_CleanupOrphanStorageFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupOrphanStorageFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).CleanupOrphanStorageFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_CleanupOrphanStorageFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).CleanupOrphanStorageFiles(ctx, req.(*CleanupOrphanStorageFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeboxMgr_ServiceDesc is the grpc.ServiceDesc for CubeboxMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeboxMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.v1.CubeboxMgr",
	HandlerType: (*CubeboxMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CubeboxMgr_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _CubeboxMgr_Destroy_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CubeboxMgr_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CubeboxMgr_Update_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _CubeboxMgr_Exec_Handler,
		},
		{
			MethodName: "AppSnapshot",
			Handler:    _CubeboxMgr_AppSnapshot_Handler,
		},
		{
			MethodName: "CommitSandbox",
			Handler:    _CubeboxMgr_CommitSandbox_Handler,
		},
		{
			MethodName: "RollbackSandbox",
			Handler:    _CubeboxMgr_RollbackSandbox_Handler,
		},
		{
			MethodName: "CleanupTemplate",
			Handler:    _CubeboxMgr_CleanupTemplate_Handler,
		},
		{
			MethodName: "ListSandboxSnapshots",
			Handler:    _CubeboxMgr_ListSandboxSnapshots_Handler,
		},
		{
			MethodName: "ListLocalSnapshots",
			Handler:    _CubeboxMgr_ListLocalSnapshots_Handler,
		},
		{
			MethodName: "GetLocalSnapshot",
			Handler:    _CubeboxMgr_GetLocalSnapshot_Handler,
		},
		{
			MethodName: "GetStorageMetrics",
			Handler:    _CubeboxMgr_GetStorageMetrics_Handler,
		},
		{
			MethodName: "InspectStorageVolumes",
			Handler:    _CubeboxMgr_InspectStorageVolumes_Handler,
		},
		{
			MethodName: "CleanupOrphanStorageFiles",
			Handler:    _CubeboxMgr_CleanupOrphanStorageFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportTemplateRootfsArtifact",
			Handler:       _CubeboxMgr_ExportTemplateRootfsArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/services/cubebox/v1/cubebox.proto",
}
